//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tshirt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int loginId { get; set; }
        public string loginName { get; set; }
        public string loginRole { get; set; }
        public string loginPassword { get; set; }
        public string loginEmail { get; set; }
    }
}
